
[profile.dev.package.pyo3]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[workspace]
members = ["nophp", "macros", "server", "lexer"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
get_first = "allow"
